config/routes.rb
Rails.application.routes.draw do
  get '/' => 'site#index'
  resources :movies do
    resources :reviews
  end
  resources :cast_members

end

app/models/cast_member.rb
class CastMember < ActiveRecord::Base
	has_and_belongs_to_many :movies
	validates :full_name, uniqueness: true
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_and_belongs_to_many :cast_members
	has_many :reviews
	validates :poster, presence: true
	validates :title, uniqueness: true

	def self.last_updated_movies(number)
		Movie.limit(number).order(created_at: :asc)
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :movie
	validates :reviewer, presence: true
	validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cast_controller.rb
class CastController < ApplicationController
	def show
		@cast = CastMember.find params[:id]
	end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	def index
		@movies = Movie.last_updated_movies(5)
	end

	def show
		@movie = Movie.find params[:id]

		render layout: 'movie'
	end
	
	def edit
		@movie = Movie.find params[:id]
	end

	def update
		@movie = Movie.find params[:id]
		if @movie.update_attributes 
			redirect_to action: 'index', controller: 'movies', movie_id: @movie.id
		else
			flash[:alert] = "Something hasn't been OK..."
			
			@errors = @entry.errors.full_messages
			render 'edit'
		end
	end

	
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def index
		@movie = Movie.find params[:movie_id]
		@reviews = @movie.reviews
	end

	def new
		@movie = Movie.find params[:movie_id]
		@review = @movie.reviews.new
	end

	def create
		@movie = Movie.find params[:movie_id]
		@review = @movie.reviews.new review_params

		if @review.save
			redirect_to action: 'index', controller: 'reviews', movie_id: @movie.id
		else
			render 'new'
		end
	end

	def update
		@obj = Obj.find(params[:id])
		if @obj.update_attributes(params[:obj])
			rediredt_to'/obks/<@obj.id'
		else
			@errors = obj.errors.full_messages
			render 'edit'
		end
	end

	private

	def review_params
		params.require(:review).permit(:reviewer, :content)
	end


end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cast_helper.rb
module CastHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/cast/show.html.erb
<% content_for :header do %>
	<h1><%= @cast.full_name %> </h1>
<% end %>
<% content_for :body do %>
<ul>

<% @cast.movies.each do |a| %>

<li><%= a.title %></li>
<% end %>
</ul>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movies</title>
  <!-- <link rel="shortcut icon" href="/PATH_TO_STATIC_FAVICON/favicon.ico" type="image/x-icon"> -->
  <link rel="icon" href="../favicon.ico" type="image/x-icon">
  <%= stylesheet_link_tag    'application', media: 'all'  %>
  
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<footer id="nav">
	<div class="menu_buttons"><%= button_to('Movies', movies_path, :method => "get") %></div>
	<div class="menu_buttons"><%= button_to('Cast Members', cast_members_path, :method => "get") %></div>
</footer>
</body>
</html>

app/views/layouts/cast.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= @cast.full_name %></title>
	 <%= stylesheet_link_tag    'application', media: 'all' %>
  
  <%= csrf_meta_tags %>
</head>
<body>
	
	<header>
	<%= yield :header %>
	</header>
	
	<%= yield :body %>

	<footer>Ironhack&copy;&reg; | All rights reserved</footer>
	
</body>
</html>

app/views/layouts/movie.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= @movie.title %></title>
	  <%= stylesheet_link_tag    'application', media: 'all' %>
  
  <%= csrf_meta_tags %>
</head>
<body>

	<header>
	<%= yield :header %>
	</header>
	
	<%= yield :body %>

	<footer>Ironhack&copy;&reg; | All rights reserved</footer>

</body>
</html>

app/views/movies/edit.html.erb
<%= form_for [@movie] do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<br>

	<%= f.label :poster %>
	<%= f.text_field :poster %>
	<br>

	<%= f.label :plot %>
	<%= f.text_field :plot %>
	<br>

	<%= f.label :year %>
	<%= f.text_field :year %>
	<br>

	<%= f.submit 'Save' %>

<% end %>

app/views/movies/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<style>
	table, tr, td {
		border: 1px solid black;
	}
</style>
<body>
	<table>
		<tr><td>Title</td><td>Poster</td></tr>
		<% @movies.each do |movie| %>
		<tr>
			<td><%= link_to(movie.title, movie_path(movie)) %></td>
			<td><img src="<%= movie.poster %>"></td>
		</tr>
		<% end %>
	</table>
</body>
</html>

app/views/movies/show.html.erb
<% content_for :header do %>
	<h1><%= @movie.title %> </h1>
<% end %>
<% content_for :body do %>
	<table>
		<tr>
		<td  class="title">Title</td>
		<td > <%= @movie.title%> <%= link_to('Edit', edit_movie_path(@movie)) %> </td>
		</tr>

		<tr>
		<td class="title">Poster</td>
		<td> <img src='<%= @movie.poster %>'> <%= link_to('Edit', edit_movie_path(@movie)) %> </td>
		</tr>

		<tr>
		<td class="title">Plot</td>
		<td> <%= @movie.plot %> <%= link_to('Edit', edit_movie_path(@movie)) %> </td>
		</tr>

		<tr>
		<td class="title">Year</td>
		<td> <%= @movie.year %> <%= link_to('Edit', edit_movie_path(@movie)) %> </td>
		</tr>

		<tr>
		<td class="title"> Cast</td>
		<td>
			<% @movie.cast_members.each do |member| %>
			<%= member.full_name + ', '%>
			<% end %>
		</td>
		</tr>	
		</table>
		<div class="button">
			<% if @movie.reviews.present? %>
				<%= button_to('Reviews', movie_reviews_path(@movie), :method => "get") %>
			<% else %>
				<%= button_to('Be the First to Coment!', new_movie_review_path(@movie.id, 'reviews'), :method => "get") %>
			<% end %>
		</div>
		<div class="button">
			<%= button_to('Movies', movies_path, :method => "get") %>
		</div>
		<div class="button">
			<%= button_to('Cast Members', cast_members_path, :method => "get") %>
		</div>
<% end %>

app/views/reviews/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<% @reviews.each do |e| %>
<div class="big">
	<div class="header"><%= e.reviewer %></div>
	<div><%= e.content %></div> 
	<div class='header'><%= time_ago_in_words(e.created_at) %>...</div>
</div>
<% end %>

<div class="button">
	<div class="button">
	<%= button_to('Return', movie_path(@movie), :method => "get") %>
	</div>

	<div class="button">
		<%= button_to('Create a review!', new_movie_review_path(@movie), :method => "get") %>
	</div>
</div>
</body>
</html>

app/views/reviews/new.html.erb
<%= form_for [@movie, @review] do |f|%>
	<div>
		<div class="button"><%= f.label :reviewer %></div>
		<div class="button"><%= f.text_field :reviewer%></div>
		<div class="red">
			<% @review.errors[:reviewer].each do |error_msg| %>
			  <%= error_msg %>
			<% end %>	
		</div>
	</div>
	<br>
	<div>
		<div class="button"><%= f.label :content %></div>
		<div class="button"><%= f.text_field :content %></div>
		<div class="red">
			
			<% @review.errors[:content].each do |error_msg| %>
			  <%= error_msg %>
			<% end %>
		</div>
	</div>
	<br>

	<%= f.submit 'Save'%>
<% end %>

app/views/site/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Home</title>
</head>
<body>
<h1>Movies</h1>
<p>Welcome to the place where you will find your favourite movies and everything you want to know about them</p>  
</body>
</html>